### ISSUE TITLE
unrecognized import path "stathat.com/c/consistent"

### ISSUE THREAD

**Issue by hitripod** [open-falcon/transfer#10]
无法 import 导致编译失败，graph 也会遇到同样问题，重现方式：`go get stathat.com/c/consistent`

```
package stathat.com/c/consistent: unrecognized import path "stathat.com/c/consistent" (https fetch: Get https://stathat.com/c/consistent?go-get=1: dial tcp 54.231.81.225:443: i/o timeout)
```

**Comment by laiwei** [comment]
stathat 怎么又改这个包的地址了。。。
用我以前fork的repo吧 https://github.com/toolkits/consistent

**Comment by wangxingge** [comment]
这个stathat 很不方便的，不知道为什么这代码会放到主分支中，差评

**Comment by wangxingge** [comment]
这个好就用它玩了   https://github.com/toolkits/consistent

**Comment by laiwei** [comment]
transfer: https://github.com/open-falcon/transfer/commit/1cb2a3d4b87da05dee1d8c7ebe14e44800765936

graph:  https://github.com/open-falcon/graph/commit/bc891d8921abedb7847261d650411a4830da05ca

在这里修复了
