### ISSUE TITLE
给transfer推数据包太大会有问题

### ISSUE THREAD

**Issue by GaoJiasheng** [open-falcon/transfer#13]
通过RPC方式给transfer推送数据，单个包不超过200个Metrics没问题，超过200不超过1000可以发送成功但获取不到正确的放回。超过1000transfer接收不到。

**Comment by gangrenroger** [comment]
也有类似的情况，一般一个payload包含10000+的Metrics，总是只有部分成功，会不会是因为转发的时候时间乱序，导致只有部分数据推送成功。

**Comment by GaoJiasheng** [comment]
@guardrule 我这边后来解决了，是因为我rpc发送的超时时间设的太小了。transfer没问题哒，你看看你是不是这个原因导致的。
