### ISSUE TITLE
对于值叠加类型的metric应该如何统计？

### ISSUE THREAD

**Issue by toontong** [open-falcon/transfer#15]
同一个endPoint同一个metric数据，假设默认MinStep=30 Second；　　 //最小上报周期,单位sec
**多个进程**，每秒都向　falcon-agent/v1/push　推数据，
但到了transfer后，由于被Step 被处理
https://github.com/open-falcon/transfer/blob/dd263b4d2f91a733dfc16ddd4d1d484152f0f634/sender/sender.go#L145-L147

最终图表中只会按最每个MinStep周期的点值（非周期内被丢弃），即使miniStep设置为最小的1秒，不丢弃中间值，也不能对同一个endPoint同一个metric数据进行叠加。

注意上面说的多个进程。
使用场景就如一个服务的qps上报，但服务是多进程。

**Comment by laiwei** [comment]
是的，叠加在falcon中不支持，你可以考虑用statsd做一下数据聚合，再传输给falcon
