### ISSUE TITLE
会不会越界？

### ISSUE THREAD

**Issue by czxichen** [open-falcon/transfer#2]
func (this *ConnPool) fetchFree() NConn {
    if len(this.free) == 0 {
        return nil
    }

```
conn := this.free[0]
this.free = this.free[1:]
return conn
```

}
这一段有没有可能出现越界？

**Comment by laiwei** [comment]
不会越界，前面的if语句 确保了 长度大于0

**Comment by czxichen** [comment]
this.free = this.free[1:]

**Comment by czxichen** [comment]
如果len(this.free) == 1 呢？

**Comment by czxichen** [comment]
好吧，我错了
